### ISSUE TITLE
Add ability to disable context menu on video element

### ISSUE THREAD

**Issue by bodia-uz** [wix/playable#97]
Currently right click on empty space in playable, opens context menu
![image](https://user-images.githubusercontent.com/2445828/52276899-122a4180-295c-11e9-8d16-fe9a209ff9b2.png)

It would be useful if you add ability to disable context menu in player. For example we wont to disallow user download video from player (right click => "Save Video As")

**Comment by BrooklynKing** [comment]
v2.11.0
